Provide the ability to deploy extra objects
localstack/helm-charts pull request #42
Opened 2021-11-07 23:45 UTC by pstetsuk-exadel

Fixed #41

2021-11-08 00:26 UTC, cmeans requested changes
I'd suggest, one minor change.

2021-11-08 00:26 UTC, cmeans commented on charts/localstack/README.md
> +* v0.3.5: Add the ability to deploy extra objects
Wrong version...
```suggestion
* v0.3.6: Add the ability to deploy extra objects
```

2021-11-08 06:19 UTC, cmeans approved these changes
LGTM

2021-11-08 11:46 UTC, whummer commented
Great, thanks @pstetsuk-exadel ! 👍

2021-11-08 11:46 UTC, merged

2022-07-27 15:55 UTC, LaikaN57 commented
This seems a bit hammer-fisted at first glance but if this is a bitnami pattern (as stated by op in #41) then I guess this is fine :/